plugins:
  enhanced_logout_enabled:
    default: true
    client: false
  enhanced_logout_should_clear_cookies:
    default: true
    client: false
  enhanced_logout_should_clear_browser_session_history:
    default: true
    client: false    
  enhanced_logout_should_redirect:
    default: true
    client: false
  enhanced_logout_redirect_url:
    default: 'http://www.google.com'
    client: false
  enhanced_logout_custom_logout_page_html:
    default: 'Logging out'
    client: false
