plugins:
  enhancedLogout_enabled:
    default: true
    client: false
  enhancedLogout_should_clear_cookies:
    default: true
    client: false
  enhancedLogout_should_clear_browser_session_history:
    default: false
    client: false    
  enhancedLogout_should_redirect:
    default: true
    client: false
  enhancedLogout_redirect_url:
    default: 'http://www.google.com'
    client: false
  enhancedLogout_custom_logout_page_html:
    default: 'Logging out'
    client: false
  enhancedLogout_should_close_tab:
    default: false
    client: false
  enhancedLogout_scrub_browser_history:
    default: false
    client: true    
