plugins:
  enhancedlogout_enabled:
    default: true
    client: false
  enhancedlogout_shouldClearCookies:
    default: true
    client: false
  enhancedlogout_shouldClearBrowserSessionHistory:
    default: true
    client: false    
  enhancedlogout_shouldRedirect:
    default: true
    client: false
  enhancedlogout_redirectUrl:
    default: 'http://www.google.com'
    client: false
  enhancedlogout_customLogoutPageHtml:
    default: 'Logging out'
    client: false    
